services:
  tavern:
    build: ./docker
    container_name: tavern
    networks:
      - realm_proxy
    ports:
      - "8080:8080"
      - "8081:80"
    volumes:
      - ./tmp:/tmp/
    environment:
      - GO_ENV=production
      - SECRETS_FILE_PATH=/tmp/secrets
      - ENABLE_DEBUG_LOGGING=true
  caddy:
    image: caddy:latest
    container_name: realm_caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - realm_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy/conf:/etc/caddy
      - $PWD/caddy/site:/srv
      - $PWD/caddy/caddy_data:/data
      - $PWD/caddy/caddy_config:/config

networks:
  realm_proxy:
